
import { User, PGListing, Booking, UserRole } from "../types";

export const mockUsers: User[] = [
  {
    id: "user_1",
    name: "John Doe",
    email: "john@example.com",
    role: "tenant",
  },
  {
    id: "user_2",
    name: "Jane Smith",
    email: "jane@example.com",
    role: "owner",
  },
  {
    id: "user_3",
    name: "Bob Johnson",
    email: "bob@example.com",
    role: "tenant",
  },
];

export const mockPGListings: PGListing[] = [
  {
    id: "pg_1",
    ownerId: "user_2",
    name: "Sunshine PG",
    location: "Koramangala, Bangalore",
    price: 8000,
    genderPreference: "male",
    amenities: ["WiFi", "AC", "Laundry", "Food"],
    imageUrl: "https://images.unsplash.com/photo-1524230572899-a752b3835840",
    availability: true,
    description: "A peaceful PG accommodation in the heart of Koramangala with all modern amenities.",
    owner_id: "user_2",
    address: "Koramangala, Bangalore",
  },
  {
    id: "pg_2",
    ownerId: "user_2",
    name: "Green Valley PG",
    location: "Indiranagar, Bangalore",
    price: 9500,
    genderPreference: "female",
    amenities: ["WiFi", "AC", "Food", "TV", "Gym"],
    imageUrl: "https://images.unsplash.com/photo-1649972904349-6e44c42644a7",
    availability: true,
    description: "Luxury PG for women with premium amenities and 24/7 security.",
    owner_id: "user_2",
    address: "Indiranagar, Bangalore",
  },
  {
    id: "pg_3",
    ownerId: "user_2",
    name: "Urban Living PG",
    location: "HSR Layout, Bangalore",
    price: 10000,
    genderPreference: "any",
    amenities: ["WiFi", "AC", "Food", "Parking", "Security"],
    imageUrl: "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b",
    availability: true,
    description: "Modern co-living space with private rooms and shared common areas.",
    owner_id: "user_2",
    address: "HSR Layout, Bangalore",
  },
  {
    id: "pg_4",
    ownerId: "user_2",
    name: "Aashiyana PG",
    location: "Whitefield, Bangalore",
    price: 7500,
    genderPreference: "male",
    amenities: ["WiFi", "Laundry", "Food", "Parking"],
    imageUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158",
    availability: true,
    description: "Affordable PG accommodation with homely food and comfortable rooms.",
    owner_id: "user_2",
    address: "Whitefield, Bangalore",
  },
  {
    id: "pg_5",
    ownerId: "user_2",
    name: "Serene Heights PG",
    location: "Electronic City, Bangalore",
    price: 8500,
    genderPreference: "female",
    amenities: ["WiFi", "AC", "Food", "Security", "Cleaning Service"],
    imageUrl: "https://images.unsplash.com/photo-1517022812141-23620dba5c23",
    availability: true,
    description: "Safe and secure PG for women with all modern amenities and home-cooked meals.",
    owner_id: "user_2",
    address: "Electronic City, Bangalore",
  },
  {
    id: "pg_6",
    ownerId: "user_2",
    name: "Comfort Zone PG",
    location: "JP Nagar, Bangalore",
    price: 9000,
    genderPreference: "any",
    amenities: ["WiFi", "AC", "Food", "TV", "Gym", "Laundry"],
    imageUrl: "https://images.unsplash.com/photo-1524230572899-a752b3835840",
    availability: true,
    description: "Premium co-living space with excellent facilities and strategic location.",
    owner_id: "user_2",
    address: "JP Nagar, Bangalore",
  },
  {
    id: "pg_7",
    ownerId: "user_2",
    name: "Happy Stay PG",
    location: "BTM Layout, Bangalore",
    price: 7000,
    genderPreference: "male",
    amenities: ["WiFi", "Food", "Laundry", "Parking"],
    imageUrl: "https://images.unsplash.com/photo-1649972904349-6e44c42644a7",
    availability: true,
    description: "Budget-friendly PG with clean rooms and good connectivity.",
    owner_id: "user_2",
    address: "BTM Layout, Bangalore",
  },
  {
    id: "pg_8",
    ownerId: "user_2",
    name: "Digital Nest PG",
    location: "Marathahalli, Bangalore",
    price: 8200,
    genderPreference: "any",
    amenities: ["WiFi", "AC", "Food", "Security", "TV"],
    imageUrl: "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b",
    availability: true,
    description: "Tech-friendly PG with high-speed internet and modern amenities.",
    owner_id: "user_2",
    address: "Marathahalli, Bangalore",
  },
];

export const mockBookings: Booking[] = [
  {
    id: "booking_1",
    tenantId: "user_1",
    pgId: "pg_1",
    status: "confirmed",
    bookingDate: "2023-05-15",
    tenant_id: "user_1",
    pg_id: "pg_1",
  },
  {
    id: "booking_2",
    tenantId: "user_3",
    pgId: "pg_2",
    status: "pending",
    bookingDate: "2023-05-20",
    tenant_id: "user_3",
    pg_id: "pg_2",
  },
];
