import { User, PGListing, Booking, UserRole } from "../types";
import { generateUUID } from "./uuidHelper";

export const mockUsers: User[] = [
  {
    id: generateUUID(),
    name: "John Doe",
    email: "john@example.com",
    role: "tenant",
  },
  {
    id: generateUUID(),
    name: "Jane Smith",
    email: "jane@example.com",
    role: "owner",
  },
  {
    id: generateUUID(),
    name: "Bob Johnson",
    email: "bob@example.com",
    role: "tenant",
  },
];

export const mockPGListings: PGListing[] = [
  {
    id: generateUUID(),
    owner_id: mockUsers[1].id,
    name: "Sunshine PG",
    location: "Koramangala, Bangalore",
    address: "Koramangala, Bangalore",
    price: 8000,
    genderPreference: "male",
    amenities: ["WiFi", "AC", "Laundry", "Food"],
    imageUrl: "https://images.unsplash.com/photo-1524230572899-a752b3835840",
    availability: true,
    description: "A peaceful PG accommodation in the heart of Koramangala with all modern amenities.",
    ownerId: mockUsers[1].id,
  },
  {
    id: generateUUID(),
    owner_id: mockUsers[1].id,
    name: "Green Valley PG",
    location: "Indiranagar, Bangalore",
    address: "Indiranagar, Bangalore",
    price: 9500,
    genderPreference: "female",
    amenities: ["WiFi", "AC", "Food", "TV", "Gym"],
    imageUrl: "https://images.unsplash.com/photo-1649972904349-6e44c42644a7",
    availability: true,
    description: "Luxury PG for women with premium amenities and 24/7 security.",
    ownerId: mockUsers[1].id,
  },
  {
    id: generateUUID(),
    owner_id: mockUsers[1].id,
    name: "Urban Living PG",
    location: "HSR Layout, Bangalore",
    address: "HSR Layout, Bangalore",
    price: 10000,
    genderPreference: "any",
    amenities: ["WiFi", "AC", "Food", "Parking", "Security"],
    imageUrl: "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b",
    availability: true,
    description: "Modern co-living space with private rooms and shared common areas.",
    ownerId: mockUsers[1].id,
  },
  {
    id: generateUUID(),
    owner_id: mockUsers[1].id,
    name: "Aashiyana PG",
    location: "Whitefield, Bangalore",
    address: "Whitefield, Bangalore",
    price: 7500,
    genderPreference: "male",
    amenities: ["WiFi", "Laundry", "Food", "Parking"],
    imageUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158",
    availability: true,
    description: "Affordable PG accommodation with homely food and comfortable rooms.",
    ownerId: mockUsers[1].id,
  },
  {
    id: generateUUID(),
    owner_id: mockUsers[1].id,
    name: "Serene Heights PG",
    location: "Electronic City, Bangalore",
    address: "Electronic City, Bangalore",
    price: 8500,
    genderPreference: "female",
    amenities: ["WiFi", "AC", "Food", "Security", "Cleaning Service"],
    imageUrl: "https://images.unsplash.com/photo-1517022812141-23620dba5c23",
    availability: true,
    description: "Safe and secure PG for women with all modern amenities and home-cooked meals.",
    ownerId: mockUsers[1].id,
  },
  {
    id: generateUUID(),
    owner_id: mockUsers[1].id,
    name: "Comfort Zone PG",
    location: "JP Nagar, Bangalore",
    address: "JP Nagar, Bangalore",
    price: 9000,
    genderPreference: "any",
    amenities: ["WiFi", "AC", "Food", "TV", "Gym", "Laundry"],
    imageUrl: "https://images.unsplash.com/photo-1524230572899-a752b3835840",
    availability: true,
    description: "Premium co-living space with excellent facilities and strategic location.",
    ownerId: mockUsers[1].id,
  },
  {
    id: generateUUID(),
    owner_id: mockUsers[1].id,
    name: "Happy Stay PG",
    location: "BTM Layout, Bangalore",
    address: "BTM Layout, Bangalore",
    price: 7000,
    genderPreference: "male",
    amenities: ["WiFi", "Food", "Laundry", "Parking"],
    imageUrl: "https://images.unsplash.com/photo-1649972904349-6e44c42644a7",
    availability: true,
    description: "Budget-friendly PG with clean rooms and good connectivity.",
    ownerId: mockUsers[1].id,
  },
  {
    id: generateUUID(),
    owner_id: mockUsers[1].id,
    name: "Digital Nest PG",
    location: "Marathahalli, Bangalore",
    address: "Marathahalli, Bangalore",
    price: 8200,
    genderPreference: "any",
    amenities: ["WiFi", "AC", "Food", "Security", "TV"],
    imageUrl: "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b",
    availability: true,
    description: "Tech-friendly PG with high-speed internet and modern amenities.",
    ownerId: mockUsers[1].id,
  },
  {
    id: generateUUID(),
    owner_id: mockUsers[1].id,
    name: "Student House PG",
    location: "Yelahanka, Bangalore",
    address: "Yelahanka, Bangalore",
    price: 6500,
    genderPreference: "male",
    amenities: ["WiFi", "Food", "Study Rooms", "Library"],
    imageUrl: "https://images.unsplash.com/photo-1517022812141-23620dba5c23",
    availability: true,
    description: "Perfect PG for students with quiet study spaces and affordable rates.",
    ownerId: mockUsers[1].id,
  },
  {
    id: generateUUID(),
    owner_id: mockUsers[1].id,
    name: "Executive Stay PG",
    location: "MG Road, Bangalore",
    address: "MG Road, Bangalore",
    price: 12000,
    genderPreference: "any",
    amenities: ["WiFi", "AC", "Food", "Laundry", "Gym", "Swimming Pool"],
    imageUrl: "https://images.unsplash.com/photo-1524230572899-a752b3835840",
    availability: true,
    description: "Luxury PG for working professionals with premium amenities and central location.",
    ownerId: mockUsers[1].id,
  },
];

export const mockBookings: Booking[] = [
  {
    id: generateUUID(),
    tenantId: mockUsers[0].id,
    pgId: mockPGListings[0].id,
    status: "confirmed",
    bookingDate: "2023-05-15",
    tenant_id: mockUsers[0].id,
    pg_id: mockPGListings[0].id,
  },
  {
    id: generateUUID(),
    tenantId: mockUsers[2].id,
    pgId: mockPGListings[1].id,
    status: "pending",
    bookingDate: "2023-05-20",
    tenant_id: mockUsers[2].id,
    pg_id: mockPGListings[1].id,
  },
];
